### ISSUE TITLE
Refactor/rethink the way problem submissions are accounted for the contest

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#109]
# Refactoring

The logic that checks whether a code has been submitted during a contest or after a contest is spread out and not even used everywhere.

I suggest the following fix: a *single* function Contestant.semifinal_submissions (and the Contestant.qualification_submissions counterpart) that (for now) does a:

```
qs_codes = (problems.models.SubmissionCode.objects
            .select_related('submission')
            .filter(submission__challenge=challenge.name,
                    submission__user=contestant.user,
                    date_submitted__range=SUBMISSIONCODE_DATE_RANGE)
```
with the date range depending on the event we're looking at.

Then, remove completely the date range handling in `contest/staff_views.py` and use this function instead. Also use this function where it's misused in `contest/models.py`, for instance `semifinal_lines_of_code` or `semifinal_problems_score`.

# Change the way to pick those codes

Once the refactoring is done, we should change the way we account these codes. Using a date range is very fragile and can fail if an event lasts longer than we thought, etc. This is pretty dangerous, and might lead us to having incorrect scores for the contestants!

During the semifinals, we already store the current event, so a good way to change that would be to simply add a field "event" in Submission that would be null by default unless it's attached to a specific semifinal. Then we only account for the codes that have an "event" in the current contest when correcting it.

This will require a migration where we assign this "event" field for already existing codes if we find a matching event in the given date range.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/109
