### ISSUE TITLE
Disable browser autocomplete in deletion form

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#112]
We don't want the browser autocomplete to fill these fields, people should *really* manually enter everything, for something that important.

**Comment by seirl** [comment]
Better (as suggested by @Morhaus ) : autocomplete="off"

**Comment by alexkirsz** [comment]
See https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion for an even surer way.

`autocomplete="prololo"` should do the trick

**Comment by seirl** [comment]
I don't like hacks like this, if the browser doesn't respect the off attribute, it's not our problem.

**Comment by alexkirsz** [comment]
HTML has *a lot* of hacks like this, some even make it into the standard since people are so used to them... If it works today, it'll work tomorrow.

**Comment by zopieux** [comment]
This is a minor feature of a module that will be used once or twice a month. *We don't want hacks for trivial stuff*. If an IE6 user gets an autocomplete on this page, I don't give the slightest damn and neither should you.

**Comment by alexkirsz** [comment]
Please do read the article before throwing a fit. We're talking about Chrome, Firefox and IE.
