### ISSUE TITLE
Edit infos in about/constest - Age formating

### ISSUE THREAD

**Issue by Fumesover** [prologin/concours-site#121]
`[...] agés de moins de 21, organisé [...]`
It should be something like `[...] agés de moins de 21 ans, organisé [...]` I think

(Related to https://github.com/prologin/site/blob/d4976567069d11b5d87839b88ba78f5fa432e9a8/prologin/locale/fr/LC_MESSAGES/django.po#L2884)

**Comment by seirl** [comment]
Thanks. Translation issues can be fixed directly in Transifex, there's no need to open issues every time: https://github.com/prologin/site/blob/master/docs/TRANSLATING.md
