### ISSUE TITLE
Update libs

### ISSUE THREAD

**Issue by cafehaine** [prologin/concours-site#125]
Bootstrap 3 reached it's end of life as of april of last year (2017)
Fontawesome 5 exists since february of this year (2018)

**Comment by seirl** [comment]
FYI, migrating to FontAwesome 5 is probably a bad idea since a lot of icons we use aren't free anymore.

This fork was created: https://forkawesome.github.io/Fork-Awesome/

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/125
