### ISSUE TITLE
Add commentary section under each exercises

### ISSUE THREAD

**Issue by haltode** [prologin/concours-site#135]

**Comment by Elfikurr** [comment]
So it would look like a forum thread ?
Instead of having people go to the forum to discuss this exercise, we would have them post directly underneath the exercise ?
Also, why is this labelled as a bug ?

**Comment by zopieux** [comment]
How and by who will the moderation be done? This *will* get some amount of people sharing their solution and other unwanted behaviors.

**Comment by Elfikurr** [comment]
Should we perhaps approve (the staff then) the comments before they are posted ?
And notify the user if they have not been approved ?
It looks tiresome though...

**Comment by Elfikurr** [comment]
@haltode agreed it would be hard to get this running without too many problems for us.
However we could still look at adding a contact button : see #134 
Can we close this issue then ? Unless someone has a good argument to keep this ?
