### ISSUE TITLE
Some old imported SubmissionCodes have the wrong "problem" field

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#138]
For instance https://prologin.org/admin/problems/submission/55978/change/ has its `problem` attribute set to "exo4" instead of the actual exo slug.

**Comment by zopieux** [comment]
LOL so a few months/years ago I looked into this. tl;dr old imports are too broken to be recoverable. Problem names changed over time with no history of what was what. I developed a tool to compute proximity scores to guess the best replacement to use, but this wasn't precise enough and required human intervention. I abandoned the idea and I suggest you do the same. There are *hundreds* of problems for which the challenge/problem pair does not exist in `problems/`. One option could be to just delete them.

**Comment by zopieux** [comment]
By the way, this is a good candidate to be in the issue dashboard #129.

**Comment by cafehaine** [comment]
will look into it after the gcc merging

**Comment by seirl** [comment]
> One option could be to just delete them.

I'm strongly against that. A lot of legacy submissions are really interesting to look at now! The example I linked is a really good one.

I would be down to delete the missing challenges, but not the missing problems as it should be pretty easy to match what goes where. At least we should try to do that on a best effort basis.

**Comment by Elfikurr** [comment]
Other than the score computation, do we have any other issue with these ?
Else, since we do not have a suitable fix for this yet (or I do not get what it is if there is one), how could we fix the score ?

One very ugly way would be to add a regex to separate the old Submissions and ignore them.

We could also choose to ignore the Submissions without SubmissionCodes ?

**Comment by Nhqml** [comment]
If the only issue with these "legacy" submissions is the score computation, I believe another option we have is to simply force the score to 0 without deleting anything.
What do you think?

**Comment by seirl** [comment]
The obvious solution is to fix the broken associations manually.

**Comment by Nhqml** [comment]
What do you mean by "fix the broken associations"?
I believe we cannot have two submissions for the same tuple (challenge, problem, user_id) so changing the "problem" field will not work if the user already submitted code for the "new" problem.

**Comment by seirl** [comment]
Yes, you will need to merge them if there's a conflict by putting the union of the SubmissionCodes of all the entries in the new entry.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/138
