### ISSUE TITLE
Add a mail tracker module

### ISSUE THREAD

**Issue by multun** [prologin/concours-site#143]
Could be something based on https://github.com/shacker/django-todo/tree/master/todo
When a mail is received on `info@`, it is attached to an issue. if no matching thread can be found, a new issue is created

**Comment by multun** [comment]
it can be reused to implement #140

**Comment by multun** [comment]
see https://github.com/multun/django-todo

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/143
