### ISSUE TITLE
Logos des sponsors très peu visibles sur la homepage

### ISSUE THREAD

**Issue by delroth** [prologin/concours-site#15]
> ###### Originally posted 2015-10-11 15:43 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Ce que je vois quand j'accède à prologin.org : http://i.imgur.com/ttQ75cG.png

Il y a genre la moitié d'un logo qui se cache dans le coin. C'est pas super niveau visibilité.

Idée quelconque : bandeau horizontal entre les deux "parties" de la homepage.

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-11 15:44 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Ou alors bouger le bouton "All the news" à coté de "Latest news", et déplacer "More info" en bas. Mais on en verrait toujours qu'un seul, c'est dommage.

**Comment by zopieux** [comment]
> ###### Originally posted 2015-10-14 21:16 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

C'est la homepage. L'idée c'était d'avoir la frise avant tout, qui résume tout : dates, progression de la participation, etc.

Soit on met les logos dans la partie bleue, soit on casse tout le principe de la frise. Si on met les logos en avant, en horizontal, c'est les news qu'on verra plus. Je suis pas fan. C'est si important ces logos ?

**Comment by delroth** [comment]
> ###### Originally posted 2015-10-14 21:25 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Avoir de l'argent pour organiser le concours ça me semble effectivement
important.

**Comment by zopieux** [comment]
> ###### Originally posted 2015-10-24 21:18 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in c589334.
