### ISSUE TITLE
Compléter les informations personnelles au moment de soumettre le QCM

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#16]
> ###### Originally posted 2015-10-11 15:47 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Le candidat doit obligatoirement mettre un nom et une adresse valide pour qu'on lui envoie sa convocation, ça devrait être une troisième partie "Vérifier / compléter vos informations personnelles".

**Comment by zopieux** [comment]
> ###### Originally posted 2015-10-14 23:22 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Contest: add name/address fields to qualif extra-info form; fixes issue #16


→ <<cset 7173e2de2f6b>>
