### ISSUE TITLE
Exam centers map cannot load

### ISSUE THREAD

**Issue by haltode** [prologin/concours-site#175]
"This page can't load Google Maps correctly."

**Comment by zopieux** [comment]
Disclaimer, I'm not sure this fixes the issue, we might still have to enable billing on the Cloud project where this key comes from.

**Comment by seirl** [comment]
Still not fixed.

**Comment by Dettorer** [comment]
Resolving #203 would also resolve that, I'm assigning myself.

**Comment by Dettorer** [comment]
Fixed in #219
