### ISSUE TITLE
Make QCM questions optionally required

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#179]
As of now, QCM questions are all mandatory. The quiz will be marked *not completed* and shown in red even if "bonus" questions, that are optional, are not filled in.

We either need:
* a "required" (defaults to True) or "optional" (defaults to False) bool to the `Question` model
* or the ability to say "I don't know" on open-ended questions (with an obvious client-side user interface)

Brought up by prologin/site-issues#39.

**Comment by Elfikurr** [comment]
Fixed by #260
