### ISSUE TITLE
Code submission from uploaded file doesn't work

### ISSUE THREAD

**Issue by nguyentito** [prologin/concours-site#18]
> ###### Originally posted 2015-10-20 13:46 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Steps to reproduce:
- go to any exercise page
- try to submit a file using the upload form ("Vous pouvez aussi envoyer un fichier")
- observe that the submission is rejected because of the empty text field

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-24 22:12 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

problems: allow code file XOR inline code (fixes #18)


→ <<cset 9becdf287b69>>
