### ISSUE TITLE
`current_edition` shouldn't live in `request`

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#180]

**Comment by Elfikurr** [comment]
Is changing `request.current_edition` to `contest.models.Edition.objects.get(year=settings.PROLOGIN_EDITION)` acceptable ?
Also, I can see some references to `request.current_edition.year`, could we change it to `settings.PROLOGIN_EDITION` ?
I don't see why the `current_edition` shouldn't live in `request` ?
This would also fix #181

**Comment by seirl** [comment]
> Is changing `request.current_edition` to `contest.models.Edition.objects.get(year=settings.PROLOGIN_EDITION)` acceptable ?

The whole purpose of request.current_edition is to avoid having to do this request every time.

> Also, I can see some references to request.current_edition.year, could we change it to settings.PROLOGIN_EDITION ?

Nope, this is already an attribute of the model, no need to do that.

> I don't see why the current_edition shouldn't live in request ?

Because we need it from code where a request object is not available, and it has nothing to do with the request.

**Comment by Elfikurr** [comment]
> The whole purpose of request.current_edition is to avoid having to do this request every time.

So could we add cached property that returns the current edition through this query ? Thus not running the query every time ?

> Nope, this is already an attribute of the model, no need to do that.

I don't know why I wrote this, it's stupid :D

> Because we need it from code where a request object is not available, and it has nothing to do with the request.

I see !

**Comment by seirl** [comment]
The idea was to simply use the django cache for that: https://docs.djangoproject.com/en/3.0/topics/cache/#basic-usage

**Comment by Elfikurr** [comment]
Can we use django cache without setting up a cache backend ?
If not, is it not "easier" to use a cached property then ?

**Comment by seirl** [comment]
django uses local-memory caching by default.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/180
