### ISSUE TITLE
Social button registration

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#19]
> ###### Originally posted 2015-10-25 00:00 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Google, Facebook and other shits.

**Comment by cafehaine** [comment]
see http://python-social-auth.readthedocs.io/en/latest/configuration/django.html

**Comment by Elfikurr** [comment]
What was the aim of this ?
Why would we want users to connect to their social media's accounts on Prologin's website ?
For faster sharing and such perhaps ?

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/19
