### ISSUE TITLE
Don't substract malus points for example tests

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#204]
https://prologin.org/forum/general-2/ne-pas-penaliser-les-erreurs-sur-les-exemples-1184/

**Comment by Elfikurr** [comment]
Hello,
How could we differentiate example tests from all the tests ?
I don't see anything in what camisole sends back that could help, and since the score and the malus are computed in different functions, we would need some kind of identifier for the example tests.

**Comment by seirl** [comment]
We already have an identifier for the example tests.
We already compute things differently for correction and performance tests, and camisole doesn't know anything about them.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/204
