### ISSUE TITLE
Permanent URLs for the news are dead links

### ISSUE THREAD

**Issue by remi-dupre** [prologin/concours-site#205]
For example, [this news](https://prologin.org/news/2019/01/14/correction-du-ctf-2019/) provides this URL in the footer: [https://gcc.prologin.org/news/1/]().

**Comment by Elfikurr** [comment]
On [the URL you provided](https://prologin.org/news/2019/01/14/correction-du-ctf-2019/), the URL in the footer appears to be correct ?
