### ISSUE TITLE
Threads don't update date_last_post when the last post is deleted

### ISSUE THREAD

**Issue by cafehaine** [prologin/concours-site#206]
Exemple : https://prologin.org/forum/entrainement-3 .

**Comment by alarsyo** [comment]
After having a quick look at it, I'm confused:

From my understanding, [this](https://github.com/prologin/site/blob/4ecb51f6811e8787017f7793a5741c4ef6a3e1d9/prologin/forum/models.py#L184) should be called every time we delete a post, updating `date_last_post` correctly.

Am I missing something ?

**Comment by cafehaine** [comment]
What you linked is (from a quick glance at it) for updating the forum last post date when a thread is deleted, not the thread date when a post is deleted

**Comment by alarsyo** [comment]
The function I linked is part of the Thread model and gets called by `Post.delete()`, [here](https://github.com/prologin/site/blob/4ecb51f6811e8787017f7793a5741c4ef6a3e1d9/prologin/forum/models.py#L262)

**Comment by cafehaine** [comment]
You're right, my bad.

The documentation seems to indicate that overriding the delete method isn't reliable, see last part of this section: https://docs.djangoproject.com/en/2.1/topics/db/models/#overriding-predefined-model-methods

**Comment by alarsyo** [comment]
Thanks for the link, I'll see if I can reproduce and fix
