### ISSUE TITLE
GDPR data export is shown for staff members, but may result in 403

### ISSUE THREAD

**Issue by multun** [prologin/concours-site#212]

**Comment by seirl** [comment]
Can you give more details about how to reproduce?

**Comment by j4m3s-s** [comment]
Any update on this ?

**Comment by lportemo** [comment]
If a staff member goes to the profile page of a user he/she is then able to see the GDPR section of this user even if the data takeout results in 403. This is more of a UI bug than a security issue.

**Comment by multun** [comment]
This was a user reported issue, hence the lack of additional information
