### ISSUE TITLE
News display

### ISSUE THREAD

**Issue by mvy** [prologin/concours-site#22]
> ###### Originally posted 2015-10-27 08:32 by [mvy](https://bitbucket.org/mvy/) on Bitbucket

The first news of the website should be displayed in its full text! Not just the header.

There is an option to highlight an entry, but it does not serve any purpose so far. Does it keep the news on top at least?

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-05 20:10 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

homepage: show full new entries; fix issue #22


→ <<cset 1f7f590f371d>>
