### ISSUE TITLE
mailing: sent to old address

### ISSUE THREAD

**Issue by Idotno-1** [prologin/concours-site#231]
I received an email from Prologin* on the email address I used to create the account. However this email was changed later to another one. The new email address was however incorrect.

*: '[Prologin] Nouveau centre d'épreuve à l'EPFL', 2019-12-04T20:15

**Comment by zopieux** [comment]
Ca manque de debugging info. Si tu fais une recherche des utilisateurs sur l'adresse email supposément incorrecte, tu trouves rien ?

**Comment by Idotno-1** [comment]
En effet, la première addresse disposait d'un autre compte, ce qui explique pourquoi elle a reçu un mail. Comme le compte d'origine avait une adresse incorrecte, il m'avait semblé que le mail était envoyé à l'ancienne adresse, mais il s'agissait juste d'un autre compte.

Mea culpa
