### ISSUE TITLE
Le texte sur le site est difficile à lire (trop de mots par colonne)

### ISSUE THREAD

**Issue by jilljenn** [prologin/concours-site#236]
> ###### Originally posted 2016-03-18 05:30 by [jilljenn](https://bitbucket.org/jilljenn/) on Bitbucket

Par exemple sur :
https://prologin.org/about/organization#contact

Il y a beaucoup de mots par ligne, ce qui peut gêner la lecture (comprendre : ce qui fait que les gens ne lisent pas).

Ça pourrait être plutôt dans l'esprit de ce genre de blogs :
http://digerateur.xyz/2015/11/18/tri-bulle-ation/

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/236
