### ISSUE TITLE
Interschool challenge leaderboard can only be displayed while logged in

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#238]
Reported by Isabelle Colin:

> J'essaie d'accéder à la page "classement établissements " du concours prologin de cette année mais quelque soit le chemin utilisé (en direct sur votre site ou via un moteur de recherche) j'arrive sur une page de connexion.

View URL: https://prologin.org/contest/inter-school-challenge/leaderboard
View class: prologin.contest.interschool_views.LeaderboardView

**Comment by Elfikurr** [comment]
Could we simply remove the rule to access this View ?

**Comment by AurelReb** [comment]
Why are we checking permission to view the leaderboard?

https://github.com/prologin/site/blob/cdec919cf6b38c4be3a1527bc327a0e3b5fc2c97/prologin/homepage/templates/homepage/school-challenge-leaderboard.html#L3

https://github.com/prologin/site/blob/cdec919cf6b38c4be3a1527bc327a0e3b5fc2c97/prologin/contest/interschool_views.py#L21

This should be removed

**Comment by cyril-amar** [comment]
Issue fixed.
