### ISSUE TITLE
Impossible de compléter le questionnaire 

### ISSUE THREAD

**Issue by champipop** [prologin/concours-site#239]
J'ai finis de remplir toutes les question hors bonus CTF et malgré que je clique sur "enregistrer les nouvelles réponses", la ligne "Compéter le questionnaire" sur la page d’accueil reste rouge et non-coché.
![capture](https://user-images.githubusercontent.com/40273631/50547589-b540ba80-0c3c-11e9-98fb-05825e84a6d2.PNG)
Du coup je ne sais pas si mes réponses sont prises en compte vu que par exemple pour les problèmes le fait que je les ais déjà commencé est affiché par la couleur jaune.

**Comment by remi-dupre** [comment]
Bonjour,

Désolé de la réponse tardive, ton message a échappé à notre attention, la prochaine fois n'hésites pas à poser tes questions sur le forum présent sur le site, c'est plus adapté pour ce type de questions ! :)

Pour ce qui est de ta question, tout est normal, tu devrais recevoir les résultats bientôt.

**Comment by remi-dupre** [comment]
Oula !

Toutes mes excuse j'ai mal lu ton message et je n'ai pas été choqué par la ligne rouge parce que je suis daltonien.

La ligne reste non validée à moins de renseigner une réponse pour les CTF, ils restent quand même des bonus, donc pas d'inquiétude !

Désolé tout de même pour le manque de clarté !

**Comment by zopieux** [comment]
Les réponses du CTF sont optionnelles, devraient être marquées comme telles dans le backend, et la règle de coloration prendre ça en compte. C'est important que cette checklist soit limpide à interpréter, histoire de ne pas provoquer de sueurs froides inutiles.
