### ISSUE TITLE
Redirect users to home page when going to /user/register while logged in

### ISSUE THREAD

**Issue by ghost** [prologin/concours-site#242]
Quand je me connecte sur le site, j'arrive quasiment à chaque fois sur un access denied : http://i.imgur.com/slk2DFv.png

Mais si je retourne sur prologin.org, je suis bien connectée ^^"

**Comment by Elfikurr** [comment]
Bonjour @GobeletUnderscore,

Si jamais le problème intervient encore, n'hésite pas à nous le remonter !
Merci encore pour le signalement :)

Bonne journée.
