### ISSUE TITLE
[Forum] code snippet isn’t displayed correctly on mobile

### ISSUE THREAD

**Issue by LeSeulArtichaut** [prologin/concours-site#243]
Reading [this post](https://prologin.org/forum/serveur-finale-site-web-4/points-virgules-en-trop-dans-un-code-a-completer-1144/), I noticed that the code snippets were not rendering when swiping to the right: the screen is not large enough to display the entire line, but swiping doesn’t make the rest of the line appear:

![83AC03F2-8E44-4E74-8488-E95EDDC93FD8](https://user-images.githubusercontent.com/38361244/72665343-c4d99f80-3a07-11ea-8761-4759dc621943.jpeg)

### Technical information:

iPhone SE
iOS 13.3
navigator.appVersion: 5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1

**Comment by e-n-0** [comment]
I can reproduce this bug on iOS Simulator 13.7 but not on 14.0.

That was an issue with (Apple) Webkit.
I can assume that this issue was fixed with iOS 14.0.
