### ISSUE TITLE
Invalid language used for sponsors link on home page

### ISSUE THREAD

**Issue by cyril-amar** [prologin/concours-site#251]
On the home page, the link at the bottom of the sponsors' logos is in English even if the website is in French.

**Comment by Elfikurr** [comment]
![DeepinScreenshot_select-area_20200412192105](https://user-images.githubusercontent.com/22329830/79075379-c5c25a80-7cf2-11ea-8562-b798d599583c.png)

I don't see it, could you confirm whether it still happens on your side or not ?

Thanks.

**Comment by cyril-amar** [comment]
Fixed, indeed.
