### ISSUE TITLE
Sponsors on the homepage

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#27]
> ###### Originally posted 2015-10-29 01:49 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

They are hardcoded instead of being fetched from the database.

**Comment by seirl** [comment]
> ###### Originally posted 2015-11-12 02:44 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Now they just need to be displayed in random order and we're good.

**Comment by zopieux** [comment]
> ###### Originally posted 2015-11-18 17:22 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

homepage: random order for sponsors; fixes issue #27


→ <<cset e4bf83c3813b>>
