### ISSUE TITLE
Admin: Cannot add new Thread: 'NoneType' object has no attribute 'author'

### ISSUE THREAD

**Issue by AurelReb** [prologin/concours-site#271]
Hi,
There is no way to add a new thread via the Django administration. It returns the following error:
AttributeError at /admin/forum/thread/
'NoneType' object has no attribute 'author'

**Comment by Elfikurr** [comment]
FYI: after trying to add a thread through the django admin, we need to remove it manually as it has no author attribute (thus preventing us from accessing the /forum/<forum_name>/ or /admin/forum/thread/ pages).

**Comment by Elfikurr** [comment]
I believe we are supposed to add a Post, and then click on the green `+` to add a Thread linked to this Post. We won't have this error then.
However, could we add a way to create a Thread by adding a Post to it ?

**Comment by AurelReb** [comment]
Indeed, this is a way to achieve this with the admin. But we should be able to add a simple thread the same way as in the prologin website.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/271
