### ISSUE TITLE
CSS zarbi

### ISSUE THREAD

**Issue by jilljenn** [prologin/concours-site#277]
Y a comme un truc zarbi autour des cubes :sweat_smile:

![Screenshot_2020-07-26 Prologin, le concours national d'informatique](https://user-images.githubusercontent.com/1729581/88479625-d1a7f480-cf50-11ea-83e7-1740dc975ebe.png)

**Comment by cafehaine** [comment]
hint, c'est dans les assets, pas le CSS, l'image est générée avec les bandes plutôt que de le faire avec un outline/shadow/border

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/277
