### ISSUE TITLE
Archive Next and Previous Month

### ISSUE THREAD

**Issue by TheoHollender** [prologin/concours-site#278]
https://prologin.org/news/2020/05/

Dans le cas présent, le mois précédent et le mois suivants sont mars et juillet qui sont des mois écartés de 2 mois en réalité. Cependant, cela ne semble arriver que pour les mois impairs, en effet, le mois d'Avril n'a quand à lui aucun problème.
https://prologin.org/news/2020/04/

**Comment by Elfikurr** [comment]
Hello,
Certains mois sont sautés car il n'y a pas eu de news.
Donc, sauf erreur de ma part, c'est le bon comportement.
Merci pour cette issue.
À bientôt.
