### ISSUE TITLE
Display judge languages versions using the VM API

### ISSUE THREAD

**Issue by audebert** [prologin/concours-site#28]
> ###### Originally posted 2015-10-30 09:15 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

The versions of the programming environment in <https://prologin.org/train/manual> are currently hard-coded.

We should generate them using <http://vm.prologin.org/versions>.

**Comment by zopieux** [comment]
> ###### Originally posted 2015-10-31 17:53 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

problems: manual: retrieve versions from vm HTTP API, fixes issue #28


→ <<cset f0c9fc58e6e0>>
