### ISSUE TITLE
Use a sorlery-like lib to create thumbnails and resize avatar uploads

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#29]
> ###### Originally posted 2015-11-07 14:39 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

https://github.com/aidanlister/sorlery/
Last commit 2 years ago. Seems partially broken (see PR). Should be forked/cleaned-up before using.

**Comment by audebert** [comment]
> ###### Originally posted 2016-01-05 16:03 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

What about using Pillow to resize the image before saving the model?

**Comment by zopieux** [comment]
> ###### Originally posted 2016-06-02 22:16 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in 37c5f8c14bfc
