### ISSUE TITLE
Wrong order with ex-æquo in rankings

### ISSUE THREAD

**Issue by FranckCHAMBON** [prologin/concours-site#296]
I think older should be displayed higher than newer in *ex-æquo* ranked solvers.
As [an example](https://prologin.org/train/2013/qualification/scoreboard) : I just score the max as some others, and I'm ranked #°1, but on top.

I'm pretty sure some days ago, the ranking between *ex-æquo* was opposite whith `candide` last of #°1 ones, now second after me...

In this example, I should be ranked last of #°1 ones, above...

Just a 2c bug.

**Comment by seirl** [comment]
I think it's specifically coded to be random. Is that something that you disagree with, conceptually?

**Comment by FranckCHAMBON** [comment]
I just think the first who achieve a max score should keep rank 1, not the opposite.

**Comment by seirl** [comment]
Well, it's not the opposite if the order is random?

**Comment by FranckCHAMBON** [comment]
In the example given in post 1, it is. Fortunately for me, I am the last solver at max score, and placed on top. I think it should the opposite ; in this case... and in general. Not a big issue, for sure.

**Comment by Elfikurr** [comment]
I believe this is just luck, and it doesn't happen everytime.

However, it might make sense for the first one to solve to be first on the leaderboard !

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/296
