### ISSUE TITLE
Visualisation/édition du profil utilisateur

### ISSUE THREAD

**Issue by breard-r** [prologin/concours-site#3]
> ###### Originally posted 2013-09-11 19:43 by [rodolphe_breard](https://bitbucket.org/rodolphe_breard/) on Bitbucket

Les utilisateurs ne peuvent actuellement pas visualiser complètement leur profil, et encore moins l'éditer.

**Comment by breard-r** [comment]
> ###### Originally posted 2013-09-29 21:32 by [rodolphe_breard](https://bitbucket.org/rodolphe_breard/) on Bitbucket

ref #3: admins can see profile details


→ <<cset 510daf66c7a5>>

**Comment by zopieux** [comment]
> ###### Originally posted 2015-02-21 20:05 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Résolu par (approximativement) 61ef508.
