### ISSUE TITLE
"Hidden" test cases should be displayed

### ISSUE THREAD

**Issue by nguyentito** [prologin/concours-site#30]
> ###### Originally posted 2015-11-10 10:52 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Currently, the judge doesn't display any information about the results of the hidden tests, it doesn't even mention their existence! As a result, a submission that fails on a hidden test may look like it passes all tests from the point of view of a user.

The UI should be the same as in the old site: for every hidden test, say whether the program has succeeded or failed, without giving the output of the program and the expected result.

**Comment by zopieux** [comment]
> ###### Originally posted 2015-11-10 18:05 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in e8adde3.
