### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by Nhqml** [prologin/concours-site#301]
Issues reported by @FranckCHAMBON in https://github.com/prologin/site/issues/295. Moved here because they're not related to the other issues described.

---

Voilà, sinon j'ai noté deux typos générales sur le site :

Dans le footer
```diff
-Suivez nous !
+Suivez-nous !
```

À l'issue d'une soumission
```diff
-0 points de malus
+0 point de malus
```

**Comment by 96RadhikaJadhav** [comment]
@Nhqml  What I got to know here is- its about correcting the typo. I didn't get the meaning of the sentences below, but @Nhqml if you can explain it in English, I can work on it.

Voilà, sinon j'ai noté deux typos générales sur le site :

Dans le footer

-Suivez nous !
+Suivez-nous !
À l'issue d'une soumission

-0 points de malus
+0 point de malus

**Comment by Elfikurr** [comment]
Hello @96RadhikaJadhav !

Thanks you for wanting to contribute :smiley:
However, this kind of issues are done separately on Transifex, as they are about translating !

So we will fix this on Transifex, sorry :'(

Would you like to work on something else ?

**Comment by 96RadhikaJadhav** [comment]
@Elfikurr Thank you so much for considering me for another issue. Sure I would like to work :) .

**Comment by Elfikurr** [comment]
@96RadhikaJadhav if you'd like to work on something easy to start : #91 could work out for you ! Or maybe #286 
Else I have an issue that could be really useful for the website : #294

What do you think ?
Is there something in particular that you would like to work on ?

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/301
