### ISSUE TITLE
Generate medium size posters for archive heading

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#31]
> ###### Originally posted 2015-11-15 23:13 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Instead of loading a full multi-megabyte image for a small decoration.

**Comment by seirl** [comment]
> ###### Originally posted 2015-11-21 22:30 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Solved in archives repository
