### ISSUE TITLE
problems: add more details when the program is crashing

### ISSUE THREAD

**Issue by Elfikurr** [prologin/concours-site#315]
Quite a few contestants are asking about what "your program exited with code %(code)s." means ([here](https://github.com/prologin/site/blob/master/prologin/problems/models/submission.py#L92)).

We could simply say that the program crashed, or that there was a `runtime_error` (which might not be understandable for some contestants).

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/315
