### ISSUE TITLE
Please, ignore extrawhitespaces only at right when judging

### ISSUE THREAD

**Issue by FranckCHAMBON** [prologin/concours-site#318]
In function [`test_passes`](https://github.com/prologin/site/blob/master/prologin/problems/camisole.py#L55), `strip` is used at lines 64 and 72:
```python
    stdout = force_text(test['stdout'], strings_only=False, errors='replace').strip()
#...
            stdout == reference.stdout.strip())
```

Instead of `strip` method, the `rstrip` is enough for the desired job, and it will let intact output like:

```
  #
 # #
# # #
 # #
  #
```

or rather more important an awaited output like

```
   1   1 1
     1 0 0 1
 +   1 0 1 1
------------
   1 0 1 0 0
```

---

Regards,

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/318
