### ISSUE TITLE
Il faudrait pouvoir consulter le questionnaire de sélection sans se connecter

### ISSUE THREAD

**Issue by nguyentito** [prologin/concours-site#32]
> ###### Originally posted 2015-11-17 20:52 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

C'était comme ça pour l'ancien site, et c'est mieux pour attirer les curieux qui veulent juste voir la tête du concours (s'inscrire, c'est chiant !).

**Comment by zopieux** [comment]
> ###### Originally posted 2015-11-18 17:09 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

C'est déjà possible mais il faut ajouter un lien quand on est déconnecté.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-11-18 19:39 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Alors, chose très drôle : https://prologin.org/contest/2016/qualification/quiz/ est consultable en étant déco, alors que https://prologin.org/contest/2016/qualification/quiz (noter la différence infime) me redirige vers https://prologin.org/user/login/?next=/contest/2016/qualification/quiz !

**Comment by cafehaine** [comment]
Cannot reproduce anymore

**Comment by seirl** [comment]
Yes, it only happens when the finals of the current edition is over, until the start of the next edition.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/32
