### ISSUE TITLE
Un programme qui ne passe pas un teste

### ISSUE THREAD

**Issue by Ombrustou** [prologin/concours-site#321]
Mon programme retourne exactement ce qui est demandé et pourtant il ne l'accepte pas.
En effet j'ai testé 4 ou 5 fois en ajoutant ou retirant des espaces cela ne marche pas plus.
![13](https://user-images.githubusercontent.com/77807271/105407597-3907de00-5c2e-11eb-8793-0c1eac3a1645.PNG)

**Comment by Elfikurr** [comment]
Hello,

Ton programme, comme indiqué dans le sujet, doit retourner seulement **un seul des chemins possibles**.

N'hésite pas si tu as d'autres questions !

Bon courage.

**Comment by Nhqml** [comment]
Je précise que les *issues* de ce dépôt permettent de signaler des erreurs sur le site ou de proposer des améliorations.

Pour toute question ou problème futur concernant les exercices, je t'invite à écrire un post sur le [forum](https://prologin.org/forum/) ou à nous envoyer un mail à info@prologin.org si tu as besoin de partager du code.

Bon courage
