### ISSUE TITLE
Add a permission to prevent "regular" staff users from seeing some info on a user's profile

### ISSUE THREAD

**Issue by Elfikurr** [prologin/concours-site#326]

**Comment by Elfikurr** [comment]
@O-Xian we could simply prevent non-superusers from seeing personal information.
Also, we can prevent non-superusers from impersonating other users, what do you think ?

**Comment by cyril-amar** [comment]
It's always good to minimize the accesses to PII. I'm all in favor of restricting impersonation, in addition to the chilling effect of posting in the chat.
Regarding user profiles, the topic at hand is whether these accesses are necessary to perform our work or not. Maybe hide them behind a button: nobody is prevented from accessing data if needed, but it requires an active, conscious action first.

**Comment by Elfikurr** [comment]
It would be better to add a rule, in case we need to give access to some users.
(for now only superusers can see personal information)

**Comment by lportemo** [comment]
Instead of adding a rule we should create a permission on the user model and map the rule to True if the bearer has the permission else False

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/326
