### ISSUE TITLE
Afficher les épreuves régionales triées par date

### ISSUE THREAD

**Issue by nguyentito** [prologin/concours-site#33]
> ###### Originally posted 2015-11-17 21:05 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Actuellement, c'est trié par ordre d'ajout dans la DB.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-11-18 16:17 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Tiens, je me dis aussi qu'actuellement, les membres de l'équipe pour une année donnée sont triés par ID de rôle. Du coup si on rajoute des rôles ils se retrouveront en dernier.

**Comment by zopieux** [comment]
> ###### Originally posted 2015-11-22 18:45 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in 880918898bfe.
