### ISSUE TITLE
PROLOGIN_SEMIFINAL_MIN_WISH_COUNT = 0 is ignored in ContestantCompleteSemifinalManager

### ISSUE THREAD

**Issue by lportemo** [prologin/concours-site#333]
https://github.com/prologin/site/blob/a96f0c8e7256ed3ef77ec0d47155777caf5a9f76/prologin/contest/models.py#L172

This line filters out contestants that have no wish even if PROLOGIN_SEMIFINAL_MIN_WISH_COUNT is set to 0.

We should modify the query or indicate that PROLOGIN_SEMIFINAL_WISH_COUNT cannot be equal to 0

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/333
