### ISSUE TITLE
Questions in corrections are not displayed correctly

### ISSUE THREAD

**Issue by Elfikurr** [prologin/concours-site#336]
Example :

![2021-02-14-114339_742x261_scrot](https://user-images.githubusercontent.com/22329830/107874421-fbf3dc00-6eb9-11eb-81a5-1e38b3ddb288.png)

Should be

![2021-02-14-114444_750x323_scrot](https://user-images.githubusercontent.com/22329830/107874429-0910cb00-6eba-11eb-8238-5c02d931da3a.png)

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/336
