### ISSUE TITLE
Add some padding after a code block in qcm

### ISSUE THREAD

**Issue by Elfikurr** [prologin/concours-site#337]
![2021-02-14-114444_750x323_scrot](https://user-images.githubusercontent.com/22329830/107874504-673dae00-6eba-11eb-8f1f-901c408d54cf.png)

Between line 11 & "Ecrivez votre réponse ici"

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/337
