### ISSUE TITLE
Find a good way to do mass-mailing

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#34]
> ###### Originally posted 2015-11-21 23:18 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

* djmail is not asynchronous
* djmail stores everything it sends in database, which takes a lot of space (can we flush it regularly?)
* external solutions are expensive
* we always fall in spam filters :(
* we need that asap (reminder mailing in a few weeks)

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-03 23:16 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

> we need that asap (reminder mailing in a few weeks)

\*laughing uncontrollably\*

**Comment by audebert** [comment]
> ###### Originally posted 2016-01-09 23:40 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Amazon SES free tier under test:

- Sendind Quota: 	send 50000 emails per 24 hour period
- Max Send Rate: 	14 emails/second
- Maximum message size (including attachments): 10 MB per message (after base64 encoding).

See https://docs.aws.amazon.com/ses/latest/DeveloperGuide/limits.html

Requires bounce rate to be approximately <15%

Setup: use Amazon SES SMTP server, send bounces notifications to Amazon SNS then to https://github.com/ofa/django-bouncy (currently w/ https://github.com/audebert/django-bouncy patches)

**Comment by zopieux** [comment]
Implemented as the mailing module.
