### ISSUE TITLE
Javascript Issue with Base Code

### ISSUE THREAD

**Issue by TheoHollender** [prologin/concours-site#340]
Test Input before 2019 are written using Node.JS's fs file system. This causes an error on the first test case :

![image](https://user-images.githubusercontent.com/58882120/108266402-5c10a980-716a-11eb-9492-e499a5dac5a1.png)

Also before 2015 there are no base code for javascript

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/340
