### ISSUE TITLE
Rename "Regional events report"

### ISSUE THREAD

**Issue by Ab2nour** [prologin/concours-site#343]
### Quick renaming fix.
French and English version of the Prologin website.

* English : Rename "Regional events report" as "Written test"
* French : Rename "Rapport des épreuves régionales" as "Épreuves écrites"

### Why 
A lot of users are asking "Where are the previous tests" on the Discord server.

![image](https://user-images.githubusercontent.com/61651582/108600608-500a2f00-7398-11eb-9a5e-326b67ac781b.png)
![image](https://user-images.githubusercontent.com/61651582/108600629-66b08600-7398-11eb-9b44-76e73de468b1.png)

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/343
