### ISSUE TITLE
Admin Annotation Problem

### ISSUE THREAD

**Issue by TheoHollender** [prologin/concours-site#346]
During the fix of #286, I found a bug that is actually unidentified, it seems like after we get the queryset in the AdminOrderFieldsMixin class, in the prologin/utils/db module, something overwrite all the annoated values to the last annotation.

**Comment by TheoHollender** [comment]
So the problem was done by the name in the method method in db.py, it was counsidered by python as a global variable, to fix it, i used a class to simulate using __call__ a function which has a name in it's instance variables.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/346
