### ISSUE TITLE
Document generation

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#35]
> ###### Originally posted 2015-11-21 23:20 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We need an equivalent of http://oldsite.prologin.org/admin/documents to generate the documents (convocations etc).

Deadline: january 2

Beware of all the LaTeX encoding issues!

**Comment by zopieux** [comment]
> ###### Originally posted 2015-11-22 19:14 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

All the work in `documents/` is broken due to changes in the contest models: `is_approved` does not exist, one has to use `Contestant.assigned_event` instead.

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-14 20:02 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

A lot of work has been done, some tasks remain:

- Remove the sql password generation (should already be in the export), fix the password generation to match the password generation of the exported data for the challenge mode.
- Clean up the code, switch to class based views (ConvocationDocView, PasswordsDocView, PortrayalAgreementDocView etc. with a template depending on the event : semi/final), use of mix-ins to factor common behavior (headers, rendering etc).
- Fix some latex issues and add instructions to the readme (packages to install, fonts etc)
- Catch latex errors and display them on screen if the user is staff, else report it with a 500 so that we get a mail
- Authorize users to generate their own convocations
- Do an admin index view to see the list of available documents to generate

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-15 23:01 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Mostly done in c87ccac93adc9.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-16 18:46 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Done in 87ccac9.
