### ISSUE TITLE
schools: worker timeout on medium-sized school merge

### ISSUE THREAD

**Issue by cyril-amar** [prologin/concours-site#357]
On URL https://prologin.org/schools/admin/merge/70896,70002?use=70896, submitting the form will raise a 405 Method Not Allowed error, after a while.

Workflow:
- search for two schools ENS Paris Saclay
- select them and try to merge them
- replace the default "Utiliser comme base" by the one with UAI = 0940607Z.
- submit the form

**Comment by lportemo** [comment]
This has been resolved by increasing the timeout on workers.
