### ISSUE TITLE
"Choix de centres d'examen pour les épreuves régionales"

### ISSUE THREAD

**Issue by Erzzul** [prologin/concours-site#358]
![ProloginIssue](https://user-images.githubusercontent.com/93410672/139509961-1a9cd192-59d5-4ec2-8eca-ccce4169491e.PNG)

As you can see, I can't pick a selection for this box, so that I can't complete my application to the contest...

Can you help me please ?

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/358
