### ISSUE TITLE
Submission correction panel

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#36]
> ###### Originally posted 2015-11-21 23:23 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We need a way to correct the submissions, that would look like http://oldsite.prologin.org/admin/contest/2015/qcm/rendu with the same features.
@Zopieux : I can't find the "eliminated" field in the models, how do we differenciate people that we have eliminated and the ones we have not corrected yet?
In the previous database, it was done with

* resultat_demi_finale_id >= 0 : the assignation ID
* resultat_demi_finale_id = -1 : not corrected yet
* resultat_demi_finale_id = -2 : eliminated

Deadline : mid-december

**Comment by zopieux** [comment]
> ###### Originally posted 2015-12-24 15:49 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in 45a1822.
