### ISSUE TITLE
Unsecured Matrix homeserver on subdomain

### ISSUE THREAD

**Issue by austinhuang0131** [prologin/concours-site#361]
There seems to be a Matrix homeserver at `matrix.prologin.org` that allows anyone to register on.

If that is not intended, you should fix it, as it can be easily abusable to create spam accounts.

**Comment by lportemo** [comment]
Hello,

The matrix server running on matrix.prologin.org only allows registration if the account is created with a confirmed @prologin.org email address.

**Comment by austinhuang0131** [comment]
Understood.

**Comment by lportemo** [comment]
Moreover, GItHub is not the right way to report security issues. If you want to report security problems you must contact soc@prologin.org
