### ISSUE TITLE
offering a correction for problems

### ISSUE THREAD

**Issue by iamlambda** [prologin/concours-site#366]
Hey everyone (: 
What I think is something missing to the website is  a correction for each problem. The question arising is who should be able to see these corrections, people who have solved the problem, or those who didn't? Each one has its own pros and cons :  the former might give another perspective on how to solve the problem than the one used by the contestent, which would help people getting better. Whereas the latter allows people who are struggling on a certain problem to get some help and not to stay on the same problem for days.

If the staff feels like they're able to handle such taks - that is, providing clean corrections to problems - they could do it. However, if they do not, another way to get these corrections would be something following Codeforces' idea, which is letting people provide their own correction. The staff could then just pick the one(s) they think are the best.

Whatever the implementation might be, I think having corrections can only have good consequences on the website and its users.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/366
