### ISSUE TITLE
Remove Europe mention and add EPITECH restriction on about/contest

### ISSUE THREAD

**Issue by Elfikurr** [prologin/concours-site#368]
https://github.com/prologin/site/blob/4d2f68a2b514dbac37848e509ce0a9819130a3c6/prologin/pages/templates/pages/about-contest.html#L44

**Comment by rishav-karanjit** [comment]
Is this issue still open?

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/368
