### ISSUE TITLE
Twittercards do not display correctly

### ISSUE THREAD

**Issue by jilljenn** [prologin/concours-site#373]
Salut, aujourd'hui en [tweetant](https://twitter.com/jjvie/status/1502581636814319616) je n'ai pas vu le logo Prologin dans mon tweet.

En investiguant, ce post cause une [internal error](https://cards-dev.twitter.com/validator) dans le validateur Twitter.

C'est peut-être lié au fait que `robots.txt` [n'autorise pas](https://prologin.org/robots.txt) `static`.

Source : [Twitter Community](https://twittercommunity.com/t/card-error-unable-to-render-or-no-image-read-this-first/62736)

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/373
