### ISSUE TITLE
Add video of the final 2022

### ISSUE THREAD

**Issue by natch444** [prologin/concours-site#376]
If someone can add the video of the 2022 final in the archive section, it would be great ;))

**Comment by Nhqml** [comment]
Since it is uploaded on YouTube and not on Vimeo, we cannot do this except we change the way the website handle videos (therefore another issue).

**Comment by seirl** [comment]
Why not also upload it on vimeo?

**Comment by Nhqml** [comment]
Because we've reached our upload limit
