### ISSUE TITLE
LaTeX display issues on qualifications exercises

### ISSUE THREAD

**Issue by agroudiev** [prologin/concours-site#378]
Using Safari 15.6.1, LaTeX display seems to bug at places, at least on [this page](https://prologin.org/train/2023/qualification/greve):

<img width="270" alt="image" src="https://user-images.githubusercontent.com/21334131/196035900-034ae6c9-7410-4712-aae4-4e7924f8b1f8.png">
<img width="591" alt="image" src="https://user-images.githubusercontent.com/21334131/196035967-8e1f1258-c9de-48e7-b121-5a138f18c697.png">

**Comment by SKYWy** [comment]
It can be resolved by using SVG as Math Renderer (see picture), but refreshing the page reset it. As I am not familiar with safari, I can't tell you how to use SVG by default.
![image](https://user-images.githubusercontent.com/59337250/197180369-2d52e9e9-544d-4723-9c5d-cb4e838eb33e.png)
