### ISSUE TITLE
Review rules to add is_authenticated on create/update views

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#38]
> ###### Originally posted 2015-12-06 23:28 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-14 20:03 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

What's the status on this? Do you have particular places in mind that need to be reviewed?

**Comment by zopieux** [comment]
> ###### Originally posted 2016-03-07 13:03 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

The idea is to review the various `rules.py` to add `rules.is_authenticated` to the relevant `add_perm()` calls.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/38
