### ISSUE TITLE
Add custom authentication backend

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#41]
> ###### Originally posted 2015-12-22 04:35 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

... to customize authentication with:

- case-insensitive logins
- an option to login with your e-mail address

**Comment by zopieux** [comment]
> ###### Originally posted 2015-12-24 15:46 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

users: implement username and email case *insensitive* auth; fix #41


→ <<cset 5c285d872221>>
