### ISSUE TITLE
Add a way to access the results of a submission from grading panel

### ISSUE THREAD

**Issue by nguyentito** [prologin/concours-site#43]
> ###### Originally posted 2016-01-10 23:34 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Since, by design, the detailed test results are not stored in the database, there is currently no simple way when grading to know on which test a code submission has failed.

Suggestion: add a button to resubmit the code (next to the "complete version" link which leads to the problem statement). This would also be useful when we expect the score to change (changes in the set of test cases, bug fixes in the judge VM, etc.).

**Comment by audebert** [comment]
> ###### Originally posted 2016-01-11 00:45 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

contest: correction: add submit again link (resolve #43)


→ <<cset ef154037a987>>
