### ISSUE TITLE
Submission grading: give individual grades and comments for each exercise

### ISSUE THREAD

**Issue by nguyentito** [prologin/concours-site#44]
> ###### Originally posted 2016-01-10 23:48 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

There should be, under each proposed solution to an algorithmic exercise :
- a numeric field to enter a grade (out of 10)
- a textarea for free comments.

The global score should be automatically computed as a weighted sum of the grades of each exercise, with adjustable coefficients.

Before human intervention, these fields would ideally be filled automatically:
- the grade being 0 or 10 depending
- the comments being a dummy message such as "WARNING: THIS CODE HAS NOT BEEN MANUALLY CHECKED"

The objective of this proposal is both to allow more fine-grained information to be entered and to reduce the risk of human error.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-10 23:52 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

No.

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-10 23:59 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

I don't like that, it sounds cumbersome. Sometimes a general comment is good enough.

**Comment by nguyentito** [comment]
> ###### Originally posted 2016-01-11 00:08 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Perhaps the individual comments would be more of a hindrance than a help, but still, the individual grades are necessary to be able to do queries such as "which candidates have given a mostly correct solution to exercise X?" (we currently rely on automated test scores for this, but it would be nice to be able to take into account human intervention). It would also allow using a grading scale (Shloub has some arguments in favor of this) without having to manually add things up.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/44
