### ISSUE TITLE
Provide "advanced search" in grading panel

### ISSUE THREAD

**Issue by nguyentito** [prologin/concours-site#45]
> ###### Originally posted 2016-01-10 23:51 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

You don't want to have to do Python queries on the database by hand to get, say, all candidates who have a non-empty submission on exercise 4 and who have not yet been assigned.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-11 10:46 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Please exhaustively list requirements instead of just a single example.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/45
