### ISSUE TITLE
Jumbotron improvements

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#46]
> ###### Originally posted 2016-01-11 00:20 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

## General

* Add links to the 3 cubes to go to the description of the phases
* Cleanup template mess

## Qualification phase

A lot of cases need to be handled (;_;)

* When the problems are not available yet, a "coming soon" infotip
* When the qualifications are over:
    * if the user did not submit anything, "come back next year" infotip
    * else if the user did submit something
        * if the qualifications_correction is not set to True yet (flag to add to the Edition model), "come back later for the results"
        * else if qualifications_correction == True
            * if user selected for semifinals, green infotip "congratulations, you passed this step"
            * else if user not selected, red infotip "sorry, you did not pass the qualifications, come back next year"

## Semifinals

* When the qualif corrections are not done yet, left as-is with all the dates
* When the qualif corrections are done and user is selected highlight semi with center info
* When the semi corrections are done
    * if user selected for finals, green infotip "congratulations, you passed this step"
    * else if user not selected, red infotip "sorry, you did not pass the semifinals, come back next year"

## Finals
* When the semi corrections are not done yet, left as-is with the date
* When the semi corrections are done and user is selected, "You have been selected for the final" + EPITA info & links

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-11 00:22 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

With the center info and the final info, a link "download the required documents & convocation" would be useful.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-16 18:43 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed by 94b02b4.

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-20 04:31 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

First item missing: add links to the 3 cubes to go to the description of the phases

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-20 16:58 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

No. They don't convey the idea we can click on them.
