### ISSUE TITLE
Automatically fill the machine exams scores in the relevant fields of Contestant

### ISSUE THREAD

**Issue by Shir0kamii** [prologin/concours-site#48]
> ###### Originally posted 2016-01-11 11:24 by [Shir0kamii](https://bitbucket.org/Shir0kamii/) on Bitbucket

It's sad to have to launch a script to fill score fields based on informations we already have when the submission is corrected. We can instead calculate the score when we receive relevant informations.

Fields that can be auto-computed:

* `score_qualif_qcm`: **based on what scoring formula?**

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/48
