### ISSUE TITLE
Letters in French are generated with dates based on the locale

### ISSUE THREAD

**Issue by mvy** [prologin/concours-site#49]
> ###### Originally posted 2016-01-14 08:26 by [mvy](https://bitbucket.org/mvy/) on Bitbucket

For the assignment paper, the date of the session is indicated in the language of the user/staff member's locale. 

The document is in French, the date should ignore the locale and force French format.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-16 19:00 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

documents: force French locale; fix #49


→ <<cset 6ecb2236a5ac>>
