### ISSUE TITLE
Documents download do not have a proper name

### ISSUE THREAD

**Issue by mvy** [prologin/concours-site#50]
> ###### Originally posted 2016-01-14 08:35 by [mvy](https://bitbucket.org/mvy/) on Bitbucket

The download for convocations (https://prologin.org/docs/2016/semifinals/user/5306/convocation/) yields a "document.pdf" file at best, or "convocation" with some download manager.

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-14 19:53 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Add this HTTP header to the response:

Content-Disposition: inline; filename=convocation.pdf

(Find a way to factor that in all the documents views.)

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-16 18:44 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed by 87ccac9 and following commits.
