### ISSUE TITLE
Check age filled and valid automatically for submitted participation

### ISSUE THREAD

**Issue by Artifere** [prologin/concours-site#51]
> ###### Originally posted 2016-01-14 17:49 by [Artifere](https://bitbucket.org/Artifere/) on Bitbucket

Refuse automatically all candidates whose age is not filled or who is not allowed to participate because too young.

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-14 19:50 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

What?

![2016-01-14-204902_733x237_scrot.png](https://bitbucket.org/repo/danLng/images/226856706-2016-01-14-204902_733x237_scrot.png)

![2016-01-14-204913_578x221_scrot.png](https://bitbucket.org/repo/danLng/images/471463461-2016-01-14-204913_578x221_scrot.png)

Please check the validity of the issues you are reporting beforehand.
