### ISSUE TITLE
Make the wishlist for semifinal centers clickable

### ISSUE THREAD

**Issue by nguyentito** [prologin/concours-site#52]
> ###### Originally posted 2016-01-16 15:33 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

In order to prevent errors when selecting somebody's assigned semifinal center in the drop-down list, it would be nice to be able to click on one of their already displayed wishes to choose it.

(Perhaps it should warn you if the candidate is marked "Eliminated" or "Not assigned"?)

**Comment by zopieux** [comment]
> ###### Originally posted 2016-01-16 19:29 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

contest: correction: click wish to assign to semifinal; fix #52


→ <<cset 7cd395dab1ee>>
