### ISSUE TITLE
Allow users to self-delete their account

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#57]
> ###### Originally posted 2016-01-22 09:55 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

### Notes
* we can actually delete the user, this will cascade on related objects;
* **but** for thread consistency we have to take care not to delete forum posts, just *nullify* the author.

### Nice to have
* send notification to ircbot when it happens

**Comment by seirl** [comment]
> ###### Originally posted 2016-02-17 16:22 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Why not just remove the personal info fields in the user and disable it?

**Comment by zopieux** [comment]
> ###### Originally posted 2016-02-17 21:46 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

I guess we can do that instead.

**Comment by seirl** [comment]
We also need to disable account deletion for users that are currently participating in the contest. ("Contact us instead", like for modifying personal information)
