### ISSUE TITLE
Améliorer la détermination de la dernière édition du concours

### ISSUE THREAD

**Issue by breard-r** [prologin/concours-site#6]
> ###### Originally posted 2013-09-29 19:20 by [rodolphe_breard](https://bitbucket.org/rodolphe_breard/) on Bitbucket

Actuellement, la dernière team est utilisée pour connaitre l'année de l'édition la plus récente de Prologin. Cette méthode n'est pas fiable et, lorsqu'il sera créé, il faudra utiliser un modèle plus approprié. Les endroits à corriger doivent etre annotés du commentaire "Issue #6" et les commits introduisant ce bug doivent être référencés à cette issue.

**Comment by breard-r** [comment]
> ###### Originally posted 2013-09-29 19:23 by [rodolphe_breard](https://bitbucket.org/rodolphe_breard/) on Bitbucket

menu custom expand, ref issue #6


→ <<cset 4611d1b04824>>

**Comment by zopieux** [comment]
> ###### Originally posted 2015-02-21 20:03 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

C'est marqué dans le header maintenant, à côté du logo.
