### ISSUE TITLE
Download final homes of previous years

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#60]
> ###### Originally posted 2016-02-17 16:29 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

First, use this script to find the uids of the homes (in /home/prologin/rendus/associate.sh) :

    #!/bin/bash

    request="select u.uid from users u
    left join resultat_qcms r on r.user_id = u.uid
    left join profile_values fname on fname.uid = u.uid and fname.fid = 3
    left join profile_values lname on lname.uid = u.uid and lname.fid = 2
    where r.qcm_id = %s
    and trim(lower(fname.value)) like '%s%%'
    and replace(
        replace(
            trim(lower(lname.value)),
        ' ', ''),
        '-', '')
        like '%s%%'
    "

    read -s password

    while read year id invname; do
        for folder in $year/*; do
            name=$( basename $folder )
            if [ "$invname" == "0" ]; then
                fname=$( echo -n $name | head -c 1 )
                lname=$( echo -n $name | tail -c +2 )
            elif [ "$invname" == "2" ]; then
                fname=""
                lname=$name
            else
                fname=$( echo -n $name | tail -c 1 )
                lname=$( echo -n $name | head -c -1 )
            fi
            lname=$( echo "$lname" | sed 's/-//g' )
            uid=$( printf "$request" "$id" "$fname" "$lname" | tee /tmp/djfksf | \
                mysql -u prologin -p"$password" prologin | tail -n +2 )
            echo -n "$folder "
            if [ "$uid" == "" ]; then
                echo "NOT FOUND"
            else
                echo "$uid"
            fi
        done
    done <<EOF
    2007 77 2
    2008 80 1
    2009 92 1
    2010 106 1
    2011 118 0
    2013 151 0
    2014 163 0
    2015 177 0
    EOF

Then add a feature in the website to download the homes.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-02-17 21:45 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Please do any manual review if needed. I need a clean mapping of `user-id → home path`.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-06-04 15:43 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Front-end done as of 6a213e9. We still have to find previous years archives.

**Comment by seirl** [comment]
> ###### Originally posted 2016-06-19 14:42 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Done by @tobast
