### ISSUE TITLE
Improve impersonate users search

### ISSUE THREAD

**Issue by Shloub** [prologin/concours-site#61]
> ###### Originally posted 2016-03-22 22:57 by [Shloub](https://bitbucket.org/Shloub/) on Bitbucket

For instance, Artifère cannot be found by typing their name.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-04-04 19:52 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

users: impersonate: improved search & error handling; fix issue #61


→ <<cset 70e1549534b8>>
