### ISSUE TITLE
Case in impersonate users search

### ISSUE THREAD

**Issue by Shloub** [prologin/concours-site#62]
> ###### Originally posted 2016-03-26 23:16 by [Shloub](https://bitbucket.org/Shloub/) on Bitbucket

The search for users in the impersonation interface returns different results depending on the case of the pattern typed. However, it seems the case is not important for Prologin website usernames.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-04-04 19:54 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed by 70e1549534b8, along with #61.
