### ISSUE TITLE
Dashboard of automated checks for inconsistency & other issues

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#67]
> ###### Originally posted 2016-04-04 19:59 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Samples:

- wrong permissions on `problems/` (eg. readable before event starts)
- wrong permissions on `archives/` (eg. readable before event stops)
- number of pending user activations
- unassigned contestant of past events
- contestants with weird states (eg. accepted in final, not accepted in qualif)
- wrong number of qualification events (!= 1), wrong number of regionals (eg. < 5), wrong number of finals (> 1)

**Comment by zopieux** [comment]
> ###### Originally posted 2016-07-07 08:06 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Some first examples.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/67
