### ISSUE TITLE
Écrire les mentions légales

### ISSUE THREAD

**Issue by breard-r** [prologin/concours-site#7]
> ###### Originally posted 2013-09-29 20:32 by [rodolphe_breard](https://bitbucket.org/rodolphe_breard/) on Bitbucket

Il est important de mettre en place les mentions légales du site. Elles doivent comprendre :

* la dénomination ou leur raison sociale de l'association
* le siège social
* le numéro de téléphone
* le nom du directeur ou du codirecteur de la publication et, le cas échéant, celui du responsable de la rédaction
* le numéro de déclaration à al CNIL
* la destination des données nominatives, ainsi que la faculté d’opposition et le droit d’accès et de rectification
* Bonus très appréciable : les coordonnées de l'hébergeur (dénomination ou leur raison sociale, siège social, téléphone, site internet)

Sources :

* [Les mentions légales obligatoires pour un site Internet](http://blog.orealys.com/2011/07/les-mentions-legales-obligatoires-pour-un-site-internet/)
* [Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique](http://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000801164&dateTexte=&categorieLien=id) (article 6, III, 1.)

**Comment by zopieux** [comment]
> ###### Originally posted 2015-07-05 13:13 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Started in 53f2d0c: https://github.com/prologin/site/commit/53f2d0ce33d1d4f6e3855ef202965c8e3db91263#chg-prologin/pages/templates/pages/about-organization.html

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-24 21:26 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Y'a tout. L'hébergeur c'est dans le whois, ça suffit.
