### ISSUE TITLE
Automated deployment

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#72]
> ###### Originally posted 2016-05-04 17:14 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

One-click (or one-command) deployment in production (prologin@rosa).

Current workflow to be automated:

1. as `prologin`: `cd site; git pull --rebase`
    1. if needed, as `prologin`, in venv: `cd prologin; ./manage.py collectstatic --noinput`
    1. if needed, as `prologin`, in venv: `cd prologin; ./manage.py compilemessages`
    1. if needed, as `prologin`, in venv: `cd prologin; ./manage.py migrate`
2. as `root`: `systemctl restart site site-celeryworker`

Things to keep in mind:

* the deploy routine should fail super fast; potential failures:
    * there are pending migrations (apply them automatically?)
    * git working directory is not clean
    * `manage.py check` warns
* what can we do when `requirements.txt` is updated? current workflow is stop site; `pip install -Ur requirements.txt`; start site
* we should also have a way to deploy an old revision if HEAD is broken
* in case of pending migrations, should we stop site, dump (backup) the whole DB, migrate, start?

**Comment by seirl** [comment]
Implemented in https://github.com/prologin/rosa-sadm
