### ISSUE TITLE
Handle ties in ranking

### ISSUE THREAD

**Issue by cbeausei** [prologin/concours-site#74]
> ###### Originally posted 2016-05-18 11:34 by [clement_bc](https://bitbucket.org/clement_bc/) on Bitbucket

* add something to handle ties in ranking.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-05-23 17:29 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

archives: handle ties in scoreboards (HallOfFame); fix #74


→ <<cset 32ebf7d37c98>>
