### ISSUE TITLE
Add a feature to download a small, anonymized database dump

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#75]
> ###### Originally posted 2016-05-23 08:58 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

This would be useful for development.

- [x] replace personal info with random (but reproductible) data: names, email, phone, address
- [x] keep usernames or generate them reproductibly
- [x] use the same password for everybody
- [x] preserve a certain diversity in user profiles, that is:
  - staff users
  - superuser users
  - users that have/haven't contestants
  - users that have/haven't codes
  - users that have/haven't a participation history
  - users that never connected since the Drupal legacy

The idea is that this dump could at worst become public without anything being compromised.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-05-23 09:05 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Alternatively, instead of trying to anonymize existing data, we can have something that generates fake yet representative data for all apps. Having a special `.py` for that purpose in every app seems a good way to split the code, instead of having one big terrible script (see `migrate_from_drupal`).

**Comment by seirl** [comment]
This wouldn't allow people to reproduce specific behaviors encountered by users when debugging though. There could be workarounds (remote connect to a readonly database) but it's not as good.

Not saying we should do one or the other, we just need to take this into account.

**Comment by seirl** [comment]
Closing this since we now have ba7db9086c2a1460542dea83df6a061e00b36932 ; we can iterate on that and open new issues as needed.

**Comment by zopieux** [comment]
File fields are not cleaned up (eg. user.avatar, user.profile), making `save()` fail on objects with invalid paths.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/75
