### ISSUE TITLE
Duplicated content of hat when displaying an entire news

### ISSUE THREAD

**Issue by cbeausei** [prologin/concours-site#76]
> ###### Originally posted 2016-05-23 22:52 by [clement_bc](https://bitbucket.org/clement_bc/) on Bitbucket

Possible action: remove the content of the hat when displaying the whole news.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-05-24 09:10 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Nope.

**Comment by zopieux** [comment]
> ###### Originally posted 2016-06-03 19:33 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

homepage: always show lead; show full contents if article is featured

Fix issue #76


→ <<cset 20ef5bf5ba1b>>
