### ISSUE TITLE
Avatars vs. Photos

### ISSUE THREAD

**Issue by breard-r** [prologin/concours-site#8]
> ###### Originally posted 2013-10-11 12:03 by [rodolphe_breard](https://bitbucket.org/rodolphe_breard/) on Bitbucket

Il faudrait, en plus des avatars, permettre aux utilisateurs d'uploader une photo (optionnelle). Cette photo doit être utilisée, si présente, dans la page de la l'équipe au lieux des avatars.

**Comment by seirl** [comment]
> ###### Originally posted 2014-01-19 15:14 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

(Il faudra faire attention à ne permettre cet upload qu'aux membres de l'asso).

**Comment by zopieux** [comment]
> ###### Originally posted 2015-02-11 14:19 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Staff members can have another, "official" profile picture. Fixes #8.


→ <<cset 600403506a0a>>
