### ISSUE TITLE
forum: add a way to check if a thread has new unread messages

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#81]
> ###### Originally posted 2017-02-07 11:35 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

**Comment by cafehaine** [comment]
What would be the best way to do this?

I currently see two ways of doing it:

1. A "LastViewed" model with tho following attributes:
   - a user foreign key
   - a thread foreign key
   - a post foreign key containing the last viewed post in a thread
2. A "LastViewed" model with the following attributes:
   - a user foreign key
   - a thread foreign key
   - a datetime field containing the last time the user opened a thread

Advantages of first method:
- Simpler ?

Advantages of second method:
- Will mark as unread if a post is modified

**Comment by seirl** [comment]
Solution 1 looks less fragile.
