### ISSUE TITLE
Remove djmail dependency or adapt mailing to it

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#87]
* only one place to store & manage emails
* needs django-bouncy integration for bounce/complaint state (easier if home made)
* the only real dependency on djmail is `prologin.email.send_email` but at the moment `mailing.models` only works for batches

**Comment by zopieux** [comment]
FYI Amazon SNS endpoint for bounces (and bounces only) is set up at https://prologin.org/bouncy. It uses a standalone user DB for auth.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/87
