### ISSUE TITLE
printing a null byte results in the exercise correction result never being displayed

### ISSUE THREAD

**Issue by multun** [prologin/concours-site#89]
The correction request is properly processed by the camisole backend, seems to be dequeued from the celery queue, but the score never gets updated.

minimal test case:
```c
#include <stdio.h> 
int main()
{
  printf("%c", 0); 
  return 0; 
}
```

**Comment by multun** [comment]
it seems to be because of json not being able of encoding binary data. (not sure though)
we could:
 * use another format, such as msgpack
 * encode stderr and stdout using base64
 * encode stderr and stdout using integer arrays

**Comment by seirl** [comment]
Fixed since we migrated to a newer camisole version with msgpack, and we store the binary result in database.
