### ISSUE TITLE
Le HTML du formulaire d'inscription n'est pas valide

### ISSUE THREAD

**Issue by breard-r** [prologin/concours-site#9]
> ###### Originally posted 2014-03-20 20:03 by [rodolphe_breard](https://bitbucket.org/rodolphe_breard/) on Bitbucket

Dans le formulaire d'inscription, le captcha génère du HTML qui ne passe pas la validation par l'outil du w3c.

**Comment by zopieux** [comment]
> ###### Originally posted 2015-10-15 12:06 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

NoCaptcha. Problem solved.
