### ISSUE TITLE
Highlight current qualification problems in /train/ during qualifications

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#91]

**Comment by Elfikurr** [comment]
Do you just want to highlight it, in bold or with some color ?
Or maybe we could think of putting the current's year information on its own line ?
A bigger part "This year's problems" and then another section "Last years' problems" perhaps ?

**Comment by zopieux** [comment]
Yeah @Elfikurr having a different style for the current year could work indeed.

**Comment by seirl** [comment]
Suggestion: 
![image](https://user-images.githubusercontent.com/4927883/91641476-efbbb580-ea24-11ea-8f62-3409ac73a837.png)

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/91
