### ISSUE TITLE
Users: changing mail address does not trigger a new validation

### ISSUE THREAD

**Issue by zopieux** [prologin/concours-site#94]
Thus allowing users to put any invalid mail, after initial validation.

**Comment by cafehaine** [comment]
Thought about this for a bit, what "safe way" is there to do this ?
Because if the user makes a typo in the new email, and we start another activation, they'll be locked out of the account

**Comment by zopieux** [comment]
We have to implement the concept of "new mail requests" that go into a dedicated table. We only update the profile email when user has visited the activation page.

But to be honest, this should be part of a more general upgrade of the user/profile stuff, eg. by allowing multiple addresses, similar to what GitHub does. I'm sure there is a nice Django library that does that for us out there, but one has to find it.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/94
