### ISSUE TITLE
Add a way to know the last visit of an user

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#96]
Currently we don't know when an user last visited the website. We know the last *connection*, but you can keep the same connection for a long time, if you ask the website to remember you. Instead of relying on the last connection, we should rely on the last visit to disable old accounts. This is not stored anywhere, so we'll need to wait to have some backlog.

**Comment by seirl** [comment]
Actually, the cookies last for 2 weeks, so to get the "worst case" of the last visit, we just need to use last_connection + settings.SESSION_COOKIE_AGE .

**Comment by seirl** [comment]
Nevermind, the cookie is refreshed every time: https://stackoverflow.com/questions/30098186/django-is-the-session-cookie-expiry-time-updated-when-session-data-is-modified

**Comment by Elfikurr** [comment]
Why would this be useful ?
Also, are we sure it's a good idea to add another cookie (or something like this) to track user activity when we're not doing so well on the GDPR compliance part ?
What do you think @O-Xian  ?

**Comment by lportemo** [comment]
With this we could track whether a user has been inactive for more than 3 years (see GDPR) if so we could delete his/her account.

**Comment by Elfikurr** [comment]
> With this we could track whether a user has been inactive for more than 3 years (see GDPR) if so we could delete his/her account.

Hum I see, but then it becomes a GDPR conumdrum : adding a tracking cookie to be GDPR compliant ... :D

**Comment by seirl** [comment]
We're not adding a tracking cookie, and I don't know what makes you think tracking inactive accounts to stop sending them e-mails would be an issue GDPR-wise.

> With this we could track whether a user has been inactive for more than 3 years (see GDPR) if so we could delete his/her account.

The GDPR doesn't require that.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/96
